version: "3"

services:
  frontend:
    build: ./frontend
    command: npm run start-watch
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/user/app
      - /user/app/node_modules
  
  backend:
    build: ./backend
    command: uvicorn main:app --reload --host 0.0.0.0
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/app

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
  
  mongo:
    image: mongo
    # command: mongod --bind_ip 0.0.0.0
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - /db:/data/db