# render.yml

build:
  frontend:
    context: ./frontend
    dockerfile: ./frontend/Dockerfile
  backend:
    context: ./backend
    dockerfile: ./backend/Dockerfile

services:
  web:
    image: backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 1 --uds /tmp/uvicorn.sock
    env:
      - PYTHONUNBUFFERED=1
    volumes:
      - type: bind
        source: ./backend
        target: /app
      - type: volume
        name: uvicorn-sock
        target: /tmp/uvicorn.sock
    ports:
      - 8000:8000
    depends_on:
      - redis

  frontend:
    image: frontend
    command: npm run start
    env:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - type: bind
        source: ./frontend
        target: /app
      - type: volume
        name: node-modules
        target: /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - web

  redis:
    image: redis:latest
    volumes:
      - type: volume
        name: redis-data
        target: /data
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  node-modules:
  redis-data:
  uvicorn-sock:
