# render.yml

build:
  frontend:
    context: ./frontend
    dockerfile: Dockerfile
  backend:
    context: ./backend
    dockerfile: Dockerfile

services:
  frontend:
    image: frontend
    command: npm run start-watch
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/user/app
      - /user/app/node_modules
  
  backend:
    image: backend
    command: uvicorn main:app --reload --host 0.0.0.0
    ports:
      - 8000:8000
    volumes:
      - ./backend:/usr/app

  redis:
    image: redis
    volumes:
      - ./data:/data
    ports:
      - 6379:6379